name: lidarSuit

channels:
  - defaults
  - conda-forge

dependencies:
 - python=3.8
 - xarray=2022.3.0
 - xrft=0.4.1
 - pandas=1.4.2
 - numpy=1.22.3
 - netCDF4=1.5.8
 - matplotlib=3.5.1
 - click=8.1.2
 - xarray-datatree=0.0.9
 - pip
 - pip:
     - gdown==4.5.1
     - lidarSuit==0.1.6
